version: '3'
services:
  mlflow:
    image: 'mlflow'
    ports:
      - '5000:5000'
    restart: always
    environment:
      - DEFAULT_ARTIFACT_ROOT=
      - BACKEND_STORE_URI=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
